### PR TITLE
switched Travis dist to Bionic

### PR DESCRIPTION
**Pull request by kuraobi**

### CODE REVIEW

**Comment by stof** [comment]
some jobs must stay on trusty (and maybe some on xenial), due to older PHP versions being unavailable on newer versions of the dist.

**Comment by kuraobi** [comment]
Yes, that's what I was checking. Weirdly, 18.04 has PHP5.3 but not 5.4-7.0...

**Comment by stof** [comment]
no. for PHP 5.3, we were already forcing a specific dist (because even trusty does not have it)

**Comment by kuraobi** [comment]
Yes I hadn't noticed first. Sorry I'm new to Travis 🤦‍♂ anyway, it works when using bionic for 7.4

**Pull request merged**
