### PR TITLE
Use Symfony code style

### PR DESCRIPTION
**Pull request by peter-gribanov**
Fix [errors](https://styleci.io/analyses/qxj51b) of [Symfony code style](https://styleci.readme.io/docs/presets#section-symfony)

### CODE REVIEW

**Comment by stof** [comment]
data files are auto-generated. So they must not be modified by hand

**Comment by peter-gribanov** [comment]
@stof i add data folder to ignore list

**Comment by everzet** [comment]
First, thanks for contribution! That said, I struggle to see the value this change brings. Can you elaborate on why do you believe this change is necessary and who's life it makes easier?

**Comment by peter-gribanov** [comment]
@everzet you want me to explain what the [code style](https://en.wikipedia.org/wiki/Programming_style) is and what is the benefit of enforcing it?

**Comment by everzet** [comment]
Yes, except not in general, but in the context of this particular project.

**Comment by peter-gribanov** [comment]
Strange question

CS it's not a feature.
CS is needed to improve the readability of the code. 
First of all, it is needed for contributors.

Do you want to receive help from other developers?
Do you want PR to be readable?

If Yes, then you need control over CS.

**Comment by peter-gribanov** [comment]
@everzet Кость, а чем тебе собственно не нравится идея контроля за CS?

**Comment by everzet** [comment]
This is super late answer, but I will provide it anyway, in case someone else has the same question.

None of the current repository maintainers is logic/code maintainers of this repository. This repo was created from a copy-paste to release the logic on Packagist and run CI builds on Travis.

Simply put - we maintain builds and Composer package, not the codebase. If I had any desire to maintain the codebase, I'd establish a CS and refactor it, but I don't. My objective is actually the opposite - to do as little changes to this codebase as humanly possible.

If someone wants to take over maintenance of both this repo build pipeline AND codebase, I am happy to discuss :)

Hope this clarifies.

P.S. @peter-gribanov sorry for a very late answer. It's not out of disrespect. Life gets in the way.

**Pull request closed without merging**
