### PR TITLE
[git] Add .gitattributes to remove unneeded files

### PR DESCRIPTION
**Pull request by Slamdunk**

### CODE REVIEW

**Comment by stof** [comment]
the ``bin`` folder should also be excluded, as it is a development tool

**Comment by Slamdunk** [comment]
I didn't added `./bin` folder because often it's used to spread a distribution binary, like https://github.com/Behat/Behat/blob/master/bin/behat itself.

Although now there aren't distribution binaries, as a new contributor I do not feel safe by adding that folder, even suggested by a project member :fearful:

**Comment by stof** [comment]
Please add it. This package only has a development script (and there is no reason for us to ship a runtime CLI script in this package given its goal)

**Comment by Slamdunk** [comment]
Done :wink:

**Comment by Slamdunk** [comment]
Ping @stof

**Comment by stof** [comment]
thanks. and sorry for having forgotten it

**Pull request merged**
